// vue/src/views/login/index.vue
<template>
  <div class="login-container">
    <el-form
      ref="loginForm"
      :model="loginForm"
      :rules="loginRules"
      class="login-form"
    >
      <h3 class="title">vue-admin</h3>
      <el-form-item prop="username">
        <span class="svg-container">
          <svg-icon name="user" />
        </span>
        <el-input
          v-model="loginForm.username"
          name="username"
          type="text"
          placeholder="username"
        />
      </el-form-item>
      <el-form-item prop="password">
        <span class="svg-container">
          <svg-icon name="password" />
        </span>
        <el-input
          :type="pwdType"
          v-model="loginForm.password"
          name="password"
          placeholder="password"
          @keyup.enter.native="handleLogin" />
        <span class="show-pwd" @click="togglePwd">
          <svg-icon name="eye" />
        </span>
      </el-form-item>
      <el-form-item>
        <el-button
          :loading="loading"
          type="primary"
          style="width:100%;"
          @click.native.prevent="handleLogin"
        >
          Sign in
        </el-button>
      </el-form-item>
      <div class="tips">
        <span style="margin-right:20px;">username: admin</span>
        <span> password: admin</span>
      </div>
    </el-form>
  </div>
</template>
<script lang='ts'>
import { Component, Vue, Watch } from 'vue-property-decorator';
import { UserModule } from '@/store/modules/user';
import { Route } from 'vue-router';
import { isValidUsername } from '@/utils/validate';
import { ElForm } from 'element-ui/types/form';

const validateUsername = (rule: any, value: string, callback: any) => {
  if (!isValidUsername(value)) {
    callback(new Error('请输入正确的用户名'));
  } else {
    callback();
  }
};
const validatePass = (rule: any, value: string, callback: any) => {
  if (value.length < 5) {
    callback(new Error('密码不能小于5位'));
  } else {
    callback();
  }
};

@Component
export default class Login extends Vue {
  loginForm = {
    username: 'admin',
    password: 'admin',
  };
  loginRules = {
    username: [{ required: true, trigger: 'blur', validator: validateUsername }],
    password: [{ required: true, trigger: 'blur', validator: validatePass }],
  };
  loading: boolean = false;
  pwdType: string = 'password';
  redirect: string | undefined = undefined;

  @Watch('$route', { immediate: true })
  onRouteChange(route: Route) {
    this.redirect = route.query && route.query.redirect as string;
  }

  togglePwd() {
    if (this.pwdType === 'password') {
      this.pwdType = 'text';
    } else {
      this.pwdType = 'password';
    }
  }
  handleLogin() {
    (this.$refs.loginForm as ElForm).validate((valid) => {
      if (valid) {
        this.loading = true;
        UserModule.Login(this.loginForm).then((res) => {
          this.loading = false;
          this.$router.push({path: this.redirect || '/'});
        }).catch((err) => {
          this.loading = false;
        });
      } else {
        return false;
      }
    });
  }
}
</script>
<style lang="less" scoped>
.login-container {
  position: fixed;
  height: 100%;
  width: 100%;
  background-color: #2d3a4b;
  /deep/.el-input {
    display: inline-block;
    height: 47px;
    width: 85%;
    input {
      background: transparent;
      border: 0px;
      -webkit-appearance: none;
      border-radius: 0px;
      padding: 12px 5px 12px 15px;
      color: #eee;
      height: 47px;
      &:-webkit-autofill {
        box-shadow: 0 0 0px 1000px #2d3a4b inset !important;
        -webkit-box-shadow: 0 0 0px 1000px #2d3a4b inset !important;
        -webkit-text-fill-color: #fff !important;
      }
    }
  }
  /deep/.el-form-item {
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: rgba(0, 0, 0, 0.1);
    border-radius: 5px;
    color: #454545;
  }
  .login-form {
    position: absolute;
    left: 0;
    right: 0;
    width: 520px;
    max-width: 100%;
    padding: 35px 35px 15px 35px;
    margin: 120px auto;
  }
  .tips {
    font-size: 14px;
    color: #fff;
    margin-bottom: 10px;
    span {
      &:first-of-type {
        margin-right: 16px;
      }
    }
  }
  .svg-container {
    padding: 6px 5px 6px 15px;
    color: #889aa4;
    vertical-align: middle;
    width: 30px;
    display: inline-block;
  }
  .title {
    font-size: 26px;
    font-weight: 400;
    color: #eee;
    margin: 0px auto 40px auto;
    text-align: center;
    font-weight: bold;
  }
  .show-pwd {
    position: absolute;
    right: 10px;
    top: 7px;
    font-size: 16px;
    color: #889aa4;
    cursor: pointer;
    user-select: none;
  }
}
</style>

// react/src/views/login/index.tsx
import React, { ComponentType, FormEvent } from 'react';
import './index.scss';
import { Form, Icon, Input, Button, Checkbox, message } from 'antd';
import { Link, withRouter, Router, RouteComponentProps } from 'react-router-dom';
import SvgIcon from '../../components/SvgIcon';
import { FormComponentProps } from 'antd/lib/form';
import { isValidUsername } from '../../utils/validate';
import { userLogin } from '../../store/user/actions';
import { GetUrlParam } from '../../utils/pathTools';

type AllProps = FormComponentProps & RouteComponentProps;
interface IState {
  pwdType: string;
  loginLodding: boolean;
}

class Login extends React.Component<AllProps, IState> {
  state: Readonly<IState> = {
    pwdType: 'password',
    loginLodding: false,
  };
  handleSubmit = (e: React.FormEvent<any>) => {
    this.props.form.validateFields((err, values) => {
      if (!err) {
        const {username, password} = values;
        const {location} = this.props;
        const redirect = GetUrlParam(location.search, 'redirect');

        this.setState({
          loginLodding: true,
        });
        userLogin(username, password).then(() => {
          this.props.history.push(redirect || '/home');
        }).catch((error) => {
          this.setState({
            loginLodding: true,
          });
          console.log(error);
        });
      } else {
        message.error('用户名或密码错误');
      }
    });
    e.preventDefault();
  }
  handleTogglePwd = () => {
    this.setState({
      pwdType: this.state.pwdType === 'text' ? 'password' : 'text',
    });
  }
  validateUsername = (rule: any, value: string, callback: any) => {
    if (!isValidUsername(value)) {
      callback(new Error('请输入正确的用户名'));
    } else {
      callback();
    }
  }
  validatePass = (rule: any, value: string, callback: any) => {
    if (value.length < 5) {
      callback(new Error('密码不能小于5位'));
    } else {
      callback();
    }
  }
  render() {
    const {pwdType, loginLodding} = this.state;
    const {getFieldDecorator} = this.props.form;
    return (
      <div className='login-container'>
        <Form onSubmit={this.handleSubmit} className='login-form'>
          <h3 className='title'>react-admin</h3>
          <Form.Item>
            {
              getFieldDecorator('username', {
                initialValue: 'admin',
                rules: [{
                  validator: this.validateUsername,
                }],
              })(<Input
                prefix={<Icon type='user' style={{ color: 'rgba(0,0,0,.25)' }} />}
                placeholder='Username' />)
            }
          </Form.Item>
          <Form.Item>
            {
              getFieldDecorator('password', {
                initialValue: 'admin',
                rules: [{
                  validator: this.validatePass,
                }],
              })(<Input
                prefix={<Icon type='lock' style={{ color: 'rgba(0,0,0,.25)' }} />}
                type={pwdType}
                placeholder='Password'/>)
            }
              <span className='show-pwd' onClick={this.handleTogglePwd}>
                <SvgIcon name='eye' />
              </span>
          </Form.Item>
          <Form.Item>
              <Checkbox
                checked={true}
                style={{color: '#fff'}}
              >Remember me</Checkbox>
            <Link
              className='login-form-forgot'
              to='/login'
            >Forgot password</Link>
            <Button
              type='primary'
              htmlType='submit'
              className='login-form-button'
              loading={loginLodding}
            >
              Log in
            </Button>
            <div className='tips'>
              <span>username: admin</span>
              <span>password: admin</span>
            </div>
          </Form.Item>
        </Form>
      </div>
    );
  }
}

export default withRouter(Form.create({})(Login));
